[build]
  command = "npm run start"
  publish = "."

# Netlify Dev Settings
[dev]
  command = "npm run start" # Start backend
  port = 8888 # Netlify dev server port

# Redirect all requests to the backend (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Function Configuration (if needed)
[functions]
  directory = "netlify/functions"
